Milestone 2
Luzaks/bookstore-redux pull request #4
Opened 2020-07-07 19:41 UTC by bruna-genz

Hello, please take a look around, in this pull request we:

- Created components, containers, actions, and reducers directories.

- Created actions and reducers to manage the books' state.

- Initialized the Redux store with an initial state in src/index.js.

- Created the UI structure with the components: App, BooksList, BooksForm, and Book.

Currently, the books in the Redux store are being displayed on the browser, as well as the form to add more books. 
You can find the live demo here: https://booky-redux.herokuapp.com/

Gently review our project,
Thanks sincerely,
@Luzaks
@bruna-genz

2020-07-07 21:21 UTC, Redvanisation requested changes
# Changes required  ♻️ 

### Hello team  🌟

**Nice work on this project, but the following changes need to be done before moving on ⬇️** 

- **index.js** in `src/reducers` should combine the app's specific reducers.

- **book.js** reducer is not well implemented, please check all my comments below.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2020-07-07 21:21 UTC, Redvanisation commented on src/containers/BooksList.js
> +const connectedBookList = connect(mapStateToProps)(BooksList);
This can be done in line 22 like this `export default connect(mapStateToProps)(connectedBookList)`

2020-07-07 21:21 UTC, Redvanisation commented on src/reducers/books.js
> +      return { books: [...state, action.payload] };
This will add a new book instead of deleting it, change that to use the `filter` method filtering the state without the book you want to remove.

2020-07-07 21:21 UTC, Redvanisation commented on src/actions/index.js
> +      category: book.category,
You could pass only the `book.id` here, you don't need the title and the category.

2020-07-08 15:31 UTC, bruna-genz commented
Hi @Redvanisation,

We implemented the required changes, using combineReducers in src/reducers/index.js, and fixed the Books reducer removeBook action to delete the specific book using the filter method.

Thanks sincerely, 
@Luzaks
@bruna-genz

2020-07-08 15:53 UTC, shloch approved these changes
![accomplished](https://user-images.githubusercontent.com/40712459/86941116-78138d80-c13b-11ea-9b5e-188b2948c6c0.jpg)

### Good to go..........modifications made  :)

2020-07-08 16:02 UTC, Luzaks commented
@shloch @Redvanisation Thank you so much for your reviews!

2020-07-08 16:51 UTC, merged